In [1]:
import numpy as np
import pandas as pd

In [2]:
matches=pd.read_csv(r"C:\Users\raush\Downloads\ipl data analysis\matches.csv")

In [3]:
matches.head()

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,2017,Rajkot,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,2017,Indore,2017-04-08,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,2017,Bangalore,2017-04-08,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN

In [4]:
matches.shape

(756, 18)

In [5]:
matches.tail()

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
751,11347,2019,Mumbai,05/05/19,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,9,HH Pandya,Wankhede Stadium,Nanda Kishore,O Nandan,S Ravi
752,11412,2019,Chennai,07/05/19,Chennai Super Kings,Mumbai Indians,Chennai Super Kings,bat,normal,0,Mumbai Indians,0,6,AS Yadav,M. A. Chidambaram Stadium,Nigel Llong,Nitin Menon,Ian Gould
753,11413,2019,Visakhapatnam,08/05/19,Sunrisers Hyderabad,Delhi Capitals,Delhi Capitals,field,normal,0,Delhi Capitals,0,2,RR Pant,ACA-VDCA Stadium,NaN,NaN,NaN
754,11414,2019,Visakhapatnam,10/05/19,Delhi Capitals,Chennai Super Kings,Chennai Super Kings,field,normal,0,Chennai Super Kings,0,6,F du Plessis,ACA-VDCA Stadium,Sundaram Ravi,Bruce Oxenford,Chettithody Shamshuddin
755,11415,2019,Hyderabad,12/05/19,Mumbai Indians,Chennai Super Kings,Mumbai Indians,bat,normal,0,Mumbai Indians,1,0,JJ Bumrah,Rajiv Gandhi Intl. Cricket Stadium,Nitin Menon,Ian Gould,Nigel Llong

In [6]:
matches.sample()

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
468,469,2014,NaN,2014-04-25,Sunrisers Hyderabad,Delhi Daredevils,Sunrisers Hyderabad,bat,normal,0,Sunrisers Hyderabad,4,0,AJ Finch,Dubai International Cricket Stadium,M Erasmus,S Ravi,NaN

In [7]:
matches.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 756 entries, 0 to 755
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               756 non-null    int64
 1   season           756 non-null    int64
 2   city             749 non-null    object
 3   date             756 non-null    object
 4   team1            756 non-null    object
 5   team2            756 non-null    object
 6   toss_winner      756 non-null    object
 7   toss_decision    756 non-null    object
 8   result           756 non-null    object
 9   dl_applied       756 non-null    int64
 10  winner           752 non-null    object
 11  win_by_runs      756 non-null    int64
 12  win_by_wickets   756 non-null    int64
 13  player_of_match  752 non-null    object
 14  venue            756 non-null    object
 15  umpire1          754 non-null    object
 16  umpire2          754 non-null    object
 17  umpire3          119 non-null    object
dtypes: int64(5), object(13)
memory usage: 106.4+ KB

In [8]:
matches.describe()

                 id       season  dl_applied  win_by_runs  win_by_wickets
count    756.000000   756.000000  756.000000   756.000000      756.000000
mean    1792.178571  2013.444444    0.025132    13.283069        3.350529
std     3464.478148     3.366895    0.156630    23.471144        3.387963
min        1.000000  2008.000000    0.000000     0.000000        0.000000
25%      189.750000  2011.000000    0.000000     0.000000        0.000000
50%      378.500000  2013.000000    0.000000     0.000000        4.000000
75%      567.250000  2016.000000    0.000000    19.000000        6.000000
max    11415.000000  2019.000000    1.000000   146.000000       10.000000

In [9]:
matches['city']

0          Hyderabad
1               Pune
2             Rajkot
3             Indore
4          Bangalore
           ...
751           Mumbai
752          Chennai
753    Visakhapatnam
754    Visakhapatnam
755        Hyderabad
Name: city, Length: 756, dtype: object

In [10]:
matches['city'].index

RangeIndex(start=0, stop=756, step=1)

In [11]:
matches['city'].values

array(['Hyderabad', 'Pune', 'Rajkot', 'Indore', 'Bangalore', 'Hyderabad',
       'Mumbai', 'Indore', 'Pune', 'Mumbai', 'Kolkata', 'Bangalore',
       'Rajkot', 'Kolkata', 'Delhi', 'Mumbai', 'Bangalore', 'Delhi',
       'Hyderabad', 'Rajkot', 'Hyderabad', 'Indore', 'Kolkata', 'Mumbai',
       'Pune', 'Rajkot', 'Kolkata', 'Mumbai', 'Pune', 'Bangalore',
       'Kolkata', 'Chandigarh', 'Pune', 'Rajkot', 'Chandigarh',
       'Hyderabad', 'Mumbai', 'Pune', 'Delhi', 'Kolkata', 'Delhi',
       'Bangalore', 'Hyderabad', 'Delhi', 'Bangalore', 'Chandigarh',
       'Hyderabad', 'Chandigarh', 'Kanpur', 'Mumbai', 'Delhi', 'Kanpur',
       'Kolkata', 'Pune', 'Delhi', 'Mumbai', 'Bangalore', 'Bangalore',
       'Hyderabad', 'Bangalore', 'Chandigarh', 'Delhi', 'Mumbai',
       'Kolkata', 'Jaipur', 'Hyderabad', 'Chennai', 'Hyderabad',
       'Chandigarh', 'Bangalore', 'Chennai', 'Mumbai', 'Chandigarh',
       'Bangalore', 'Kolkata', 'Delhi', 'Hyderabad', 'Jaipur', 'Chennai',
       'Hyderabad', 'Chandigarh', 'Mumbai', 'Jaipur', 'Bangalore',
       'Chennai', 'Mumbai', 'Delhi', 'Kolkata', 'Jaipur', 'Bangalore',
       'Chennai', 'Hyderabad', 'Jaipur', 'Chandigarh', 'Kolkata',
       'Mumbai', 'Chandigarh', 'Delhi', 'Mumbai', 'Delhi', 'Jaipur',
       'Hyderabad', 'Kolkata', 'Bangalore', 'Kolkata', 'Mumbai',
       'Chennai', 'Chandigarh', 'Delhi', 'Chennai', 'Bangalore',
       'Kolkata', 'Jaipur', 'Hyderabad', 'Mumbai', 'Mumbai', 'Mumbai',
       'Cape Town', 'Cape Town', 'Cape Town', 'Cape Town',
       'Port Elizabeth', 'Durban', 'Cape Town', 'Durban', 'Cape Town',
       'Durban', 'Durban', 'Port Elizabeth', 'Cape Town', 'Durban',
       'Port Elizabeth', 'Centurion', 'Durban', 'Durban', 'Centurion',
       'Centurion', 'East London', 'Durban', 'Port Elizabeth',
       'Johannesburg', 'Port Elizabeth', 'Johannesburg', 'East London',
       'Durban', 'Durban', 'Centurion', 'Centurion', 'Centurion',
       'East London', 'Kimberley', 'Kimberley', 'Port Elizabeth',
       'Johannesburg', 'Kimberley', 'Centurion', 'Centurion', 'Durban',
       'Durban', 'Durban', 'Bloemfontein', 'Port Elizabeth',
       'Johannesburg', 'Johannesburg', 'Bloemfontein', 'Centurion',
       'Johannesburg', 'Durban', 'Durban', 'Centurion', 'Centurion',
       'Centurion', 'Johannesburg', 'Johannesburg', 'Mumbai', 'Mumbai',
       'Chandigarh', 'Kolkata', 'Chennai', 'Ahmedabad', 'Bangalore',
       'Kolkata', 'Delhi', 'Bangalore', 'Delhi', 'Cuttack', 'Ahmedabad',
       'Mumbai', 'Cuttack', 'Chennai', 'Mumbai', 'Bangalore',
       'Chandigarh', 'Mumbai', 'Ahmedabad', 'Chandigarh', 'Bangalore',
       'Ahmedabad', 'Mumbai', 'Delhi', 'Mumbai', 'Chennai', 'Delhi',
       'Kolkata', 'Chandigarh', 'Chennai', 'Mumbai', 'Kolkata', 'Delhi',
       'Nagpur', 'Chennai', 'Jaipur', 'Kolkata', 'Bangalore',
       'Chandigarh', 'Nagpur', 'Bangalore', 'Delhi', 'Jaipur', 'Nagpur',
       'Mumbai', 'Chennai', 'Jaipur', 'Chennai', 'Dharamsala',
       'Bangalore', 'Kolkata', 'Dharamsala', 'Delhi', 'Kolkata', 'Mumbai',
       'Mumbai', 'Mumbai', 'Mumbai', 'Chennai', 'Hyderabad', 'Kochi',
       'Delhi', 'Mumbai', 'Kolkata', 'Jaipur', 'Bangalore', 'Chandigarh',
       'Mumbai', 'Hyderabad', 'Jaipur', 'Mumbai', 'Chennai', 'Hyderabad',
       'Mumbai', 'Kolkata', 'Kochi', 'Delhi', 'Mumbai', 'Kolkata',
       'Chandigarh', 'Mumbai', 'Kolkata', 'Delhi', 'Hyderabad', 'Jaipur',
       'Chennai', 'Delhi', 'Mumbai', 'Kochi', 'Delhi', 'Jaipur',
       'Bangalore', 'Kochi', 'Kolkata', 'Jaipur', 'Chennai', 'Mumbai',
       'Delhi', 'Hyderabad', 'Chennai', 'Mumbai', 'Kochi', 'Hyderabad',
       'Bangalore', 'Kolkata', 'Mumbai', 'Bangalore', 'Chandigarh',
       'Jaipur', 'Hyderabad', 'Chandigarh', 'Jaipur', 'Chennai', 'Indore',
       'Bangalore', 'Mumbai', 'Dharamsala', 'Indore', 'Mumbai',
       'Dharamsala', 'Chennai', 'Mumbai', 'Mumbai', 'Dharamsala', 'Delhi',
       'Bangalore', 'Kolkata', 'Mumbai', 'Mumbai', 'Chennai', 'Chennai',
       'Chennai', 'Kolkata', 'Mumbai', 'Jaipur', 'Bangalore',
       'Visakhapatnam', 'Jaipur', 'Pune', 'Visakhapatnam', 'Bangalore',
       'Delhi', 'Mumbai', 'Chennai', 'Chandigarh', 'Kolkata', 'Delhi',
       'Pune', 'Kolkata', 'Bangalore', 'Mumbai', 'Jaipur', 'Bangalore',
       'Chandigarh', 'Hyderabad', 'Chennai', 'Chandigarh', 'Chennai',
       'Delhi', 'Mumbai', 'Cuttack', 'Jaipur', 'Pune', 'Chandigarh',
       'Pune', 'Delhi', 'Chennai', 'Kolkata', 'Delhi', 'Mumbai',
       'Chennai', 'Cuttack', 'Jaipur', 'Bangalore', 'Pune', 'Chennai',
       'Kolkata', 'Chandigarh', 'Mumbai', 'Bangalore', 'Delhi', 'Pune',
       'Hyderabad', 'Mumbai', 'Jaipur', 'Pune', 'Kolkata', 'Chennai',
       'Jaipur', 'Chandigarh', 'Bangalore', 'Kolkata', 'Delhi', 'Mumbai',
       'Dharamsala', 'Delhi', 'Hyderabad', 'Dharamsala', 'Pune',
       'Hyderabad', 'Jaipur', 'Pune', 'Bangalore', 'Chennai', 'Chennai',
       'Kolkata', 'Bangalore', 'Hyderabad', 'Delhi', 'Chennai', 'Pune',
       'Hyderabad', 'Jaipur', 'Mumbai', 'Chandigarh', 'Bangalore', 'Pune',
       'Delhi', 'Mumbai', 'Chennai', 'Kolkata', 'Jaipur', 'Chennai',
       'Chandigarh', 'Bangalore', 'Pune', 'Jaipur', 'Delhi', 'Hyderabad',
       'Kolkata', 'Bangalore', 'Delhi', 'Chandigarh', 'Chennai',
       'Bangalore', 'Dharamsala', 'Kolkata', 'Chennai', 'Kolkata',
       'Jaipur', 'Mumbai', 'Chennai', 'Raipur', 'Jaipur', 'Mumbai',
       'Pune', 'Hyderabad', 'Raipur', 'Chennai', 'Pune', 'Kolkata',
       'Hyderabad', 'Bangalore', 'Mumbai', 'Jaipur', 'Bangalore',
       'Jaipur', 'Mumbai', 'Hyderabad', 'Chandigarh', 'Pune', 'Delhi',
       'Pune', 'Chandigarh', 'Ranchi', 'Jaipur', 'Delhi', 'Mumbai',
       'Ranchi', 'Chennai', 'Mumbai', 'Chandigarh', 'Hyderabad',
       'Dharamsala', 'Pune', 'Bangalore', 'Hyderabad', 'Delhi', 'Delhi',
       'Kolkata', 'Kolkata', 'Abu Dhabi', 'Sharjah', 'Abu Dhabi',
       'Abu Dhabi', nan, nan, 'Sharjah', 'Abu Dhabi', 'Sharjah', nan,
       'Sharjah', nan, nan, 'Abu Dhabi', 'Abu Dhabi', 'Sharjah',
       'Sharjah', nan, 'Abu Dhabi', nan, 'Ranchi', 'Mumbai', 'Delhi',
       'Bangalore', 'Ahmedabad', 'Delhi', 'Mumbai', 'Delhi', 'Cuttack',
       'Ahmedabad', 'Bangalore', 'Delhi', 'Mumbai', 'Cuttack',
       'Bangalore', 'Hyderabad', 'Ranchi', 'Bangalore', 'Hyderabad',
       'Cuttack', 'Ahmedabad', 'Ranchi', 'Hyderabad', 'Ahmedabad',
       'Delhi', 'Hyderabad', 'Kolkata', 'Chandigarh', 'Kolkata', 'Ranchi',
       'Mumbai', 'Chandigarh', 'Bangalore', 'Kolkata', 'Chandigarh',
       'Mumbai', 'Kolkata', 'Mumbai', 'Mumbai', 'Bangalore', 'Kolkata',
       'Chennai', 'Pune', 'Chennai', 'Kolkata', 'Delhi', 'Mumbai',
       'Bangalore', 'Ahmedabad', 'Kolkata', 'Pune', 'Visakhapatnam',
       'Mumbai', 'Visakhapatnam', 'Pune', 'Ahmedabad', 'Bangalore',
       'Delhi', 'Ahmedabad', 'Visakhapatnam', 'Bangalore', 'Delhi',
       'Ahmedabad', 'Mumbai', 'Chennai', 'Delhi', 'Chandigarh', 'Kolkata',
       'Bangalore', 'Chennai', 'Delhi', 'Mumbai', 'Bangalore',
       'Hyderabad', 'Chandigarh', 'Mumbai', 'Chennai', 'Kolkata',
       'Mumbai', 'Bangalore', 'Mumbai', 'Chennai', 'Kolkata', 'Raipur',
       'Mumbai', 'Chennai', 'Hyderabad', 'Raipur', 'Chandigarh', 'Mumbai',
       'Hyderabad', 'Chandigarh', 'Mumbai', 'Bangalore', 'Hyderabad',
       'Mumbai', 'Pune', 'Ranchi', 'Kolkata', 'Mumbai', 'Kolkata',
       'Chandigarh', 'Bangalore', 'Kolkata', 'Rajkot', 'Delhi',
       'Hyderabad', 'Mumbai', 'Chandigarh', 'Bangalore', 'Hyderabad',
       'Chandigarh', 'Mumbai', 'Rajkot', 'Pune', 'Delhi', 'Hyderabad',
       'Rajkot', 'Pune', 'Chandigarh', 'Hyderabad', 'Delhi', 'Mumbai',
       'Pune', 'Delhi', 'Hyderabad', 'Rajkot', 'Pune', 'Bangalore',
       'Rajkot', 'Kolkata', 'Delhi', 'Hyderabad', 'Bangalore',
       'Chandigarh', 'Visakhapatnam', 'Kolkata', 'Chandigarh',
       'Visakhapatnam', 'Bangalore', 'Hyderabad', 'Visakhapatnam',
       'Bangalore', 'Kolkata', 'Chandigarh', 'Visakhapatnam', 'Kolkata',
       'Visakhapatnam', 'Bangalore', 'Kanpur', 'Raipur', 'Visakhapatnam',
       'Kanpur', 'Kolkata', 'Raipur', 'Bangalore', 'Delhi', 'Delhi',
       'Bangalore', 'Mumbai', 'Mohali', 'Kolkata', 'Hyderabad', 'Chennai',
       'Jaipur', 'Hyderabad', 'Bengaluru', 'Mumbai', 'Kolkata',
       'Bengaluru', 'Mohali', 'Kolkata', 'Mumbai', 'Jaipur', 'Mohali',
       'Pune', 'Kolkata', 'Bengaluru', 'Hyderabad', 'Jaipur', 'Delhi',
       'Mumbai', 'Bengaluru', 'Hyderabad', 'Delhi', 'Pune', 'Jaipur',
       'Bengaluru', 'Pune', 'Bengaluru', 'Delhi', 'Kolkata', 'Indore',
       'Pune', 'Hyderabad', 'Mumbai', 'Indore', 'Hyderabad', 'Jaipur',
       'Kolkata', 'Delhi', 'Jaipur', 'Indore', 'Delhi', 'Pune', 'Mumbai',
       'Indore', 'Kolkata', 'Mumbai', 'Bengaluru', 'Delhi', 'Jaipur',
       'Hyderabad', 'Delhi', 'Pune', 'Mumbai', 'Kolkata', 'Kolkata',
       'Mumbai', 'Chennai', 'Kolkata', 'Mumbai', 'Jaipur', 'Delhi',
       'Kolkata', 'Bengaluru', 'Hyderabad', 'Mohali', 'Delhi',
       'Hyderabad', 'Chennai', 'Mohali', 'Jaipur', 'Mumbai', 'Delhi',
       'Bengaluru', 'Chennai', 'Hyderabad', 'Bengaluru', 'Jaipur',
       'Mohali', 'Chennai', 'Mumbai', 'Jaipur', 'Kolkata', 'Mumbai',
       'Mohali', 'Kolkata', 'Hyderabad', 'Mumbai', 'Mohali', 'Hyderabad',
       'Delhi', 'Kolkata', 'Jaipur', 'Delhi', 'Hyderabad', 'Bengaluru',
       'Jaipur', 'Chennai', 'Bengaluru', 'Kolkata', 'Chennai', 'Jaipur',
       'Delhi', 'Kolkata', 'Hyderabad', 'Bengaluru', 'Chennai', 'Mumbai',
       'Mohali', 'Delhi', 'Bengaluru', 'Mohali', 'Mumbai', 'Chennai',
       'Visakhapatnam', 'Visakhapatnam', 'Hyderabad'], dtype=object)

In [12]:
matches['city'].value_counts()

Mumbai            101
Kolkata            77
Delhi              74
Bangalore          66
Hyderabad          64
Chennai            57
Jaipur             47
Chandigarh         46
Pune               38
Durban             15
Bengaluru          14
Visakhapatnam      13
Centurion          12
Ahmedabad          12
Rajkot             10
Mohali             10
Dharamsala          9
Indore              9
Johannesburg        8
Cuttack             7
Port Elizabeth      7
Ranchi              7
Abu Dhabi           7
Cape Town           7
Sharjah             6
Raipur              6
Kochi               5
Kanpur              4
Nagpur              3
East London         3
Kimberley           3
Bloemfontein        2
Name: city, dtype: int64

In [13]:
matches[['winner','player_of_match']]

                          winner player_of_match
0            Sunrisers Hyderabad    Yuvraj Singh
1         Rising Pune Supergiant       SPD Smith
2          Kolkata Knight Riders         CA Lynn
3                Kings XI Punjab      GJ Maxwell
4    Royal Challengers Bangalore       KM Jadhav
..                           ...             ...
751               Mumbai Indians       HH Pandya
752               Mumbai Indians        AS Yadav
753               Delhi Capitals         RR Pant
754          Chennai Super Kings    F du Plessis
755               Mumbai Indians       JJ Bumrah

[756 rows x 2 columns]

In [14]:
matches.iloc[1]

id                                                       2
season                                                2017
city                                                  Pune
date                                            2017-04-06
team1                                       Mumbai Indians
team2                               Rising Pune Supergiant
toss_winner                         Rising Pune Supergiant
toss_decision                                        field
result                                              normal
dl_applied                                               0
winner                              Rising Pune Supergiant
win_by_runs                                              0
win_by_wickets                                           7
player_of_match                                  SPD Smith
venue              Maharashtra Cricket Association Stadium
umpire1                                     A Nand Kishore
umpire2                                             S Ravi
umpire3                                                NaN
Name: 1, dtype: object

In [15]:
matches.iloc[1].index

Index(['id', 'season', 'city', 'date', 'team1', 'team2', 'toss_winner',
       'toss_decision', 'result', 'dl_applied', 'winner', 'win_by_runs',
       'win_by_wickets', 'player_of_match', 'venue', 'umpire1', 'umpire2',
       'umpire3'],
      dtype='object')

In [16]:
matches.iloc[1].values

array([2, 2017, 'Pune', '2017-04-06', 'Mumbai Indians',
       'Rising Pune Supergiant', 'Rising Pune Supergiant', 'field',
       'normal', 0, 'Rising Pune Supergiant', 0, 7, 'SPD Smith',
       'Maharashtra Cricket Association Stadium', 'A Nand Kishore',
       'S Ravi', nan], dtype=object)

In [17]:
matches.iloc[1].shape

(18,)

In [18]:
matches.iloc[2:6]

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
2,3,2017,Rajkot,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,2017,Indore,2017-04-08,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,2017,Bangalore,2017-04-08,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN
5,6,2017,Hyderabad,2017-04-09,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Sunrisers Hyderabad,0,9,Rashid Khan,"Rajiv Gandhi International Stadium, Uppal",A Deshmukh,NJ Llong,NaN

In [19]:
matches.iloc[2:6].city

2       Rajkot
3       Indore
4    Bangalore
5    Hyderabad
Name: city, dtype: object

In [20]:
matches[::-1]

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
755,11415,2019,Hyderabad,12/05/19,Mumbai Indians,Chennai Super Kings,Mumbai Indians,bat,normal,0,Mumbai Indians,1,0,JJ Bumrah,Rajiv Gandhi Intl. Cricket Stadium,Nitin Menon,Ian Gould,Nigel Llong
754,11414,2019,Visakhapatnam,10/05/19,Delhi Capitals,Chennai Super Kings,Chennai Super Kings,field,normal,0,Chennai Super Kings,0,6,F du Plessis,ACA-VDCA Stadium,Sundaram Ravi,Bruce Oxenford,Chettithody Shamshuddin
753,11413,2019,Visakhapatnam,08/05/19,Sunrisers Hyderabad,Delhi Capitals,Delhi Capitals,field,normal,0,Delhi Capitals,0,2,RR Pant,ACA-VDCA Stadium,NaN,NaN,NaN
752,11412,2019,Chennai,07/05/19,Chennai Super Kings,Mumbai Indians,Chennai Super Kings,bat,normal,0,Mumbai Indians,0,6,AS Yadav,M. A. Chidambaram Stadium,Nigel Llong,Nitin Menon,Ian Gould
751,11347,2019,Mumbai,05/05/19,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,9,HH Pandya,Wankhede Stadium,Nanda Kishore,O Nandan,S Ravi
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,5,2017,Bangalore,2017-04-08,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN
3,4,2017,Indore,2017-04-08,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
2,3,2017,Rajkot,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN

In [21]:
matches['winner'].value_counts()

Mumbai Indians                 109
Chennai Super Kings            100
Kolkata Knight Riders           92
Royal Challengers Bangalore     84
Kings XI Punjab                 82
Rajasthan Royals                75
Delhi Daredevils                67
Sunrisers Hyderabad             58
Deccan Chargers                 29
Gujarat Lions                   13
Pune Warriors                   12
Rising Pune Supergiant          10
Delhi Capitals                  10
Kochi Tuskers Kerala             6
Rising Pune Supergiants          5
Name: winner, dtype: int64

In [22]:
matches['player_of_match'].value_counts().head(15)

CH Gayle          21
AB de Villiers    20
DA Warner         17
MS Dhoni          17
RG Sharma         17
YK Pathan         16
SR Watson         15
SK Raina          14
G Gambhir         13
AM Rahane         12
MEK Hussey        12
V Kohli           12
AD Russell        11
A Mishra          11
DR Smith          11
Name: player_of_match, dtype: int64

In [23]:
matches[:59].player_of_match.value_counts()

NM Coulter-Nile      3
BA Stokes            3
AJ Tye               2
N Rana               2
SP Narine            2
JD Unadkat           2
Rashid Khan          2
RV Uthappa           2
KH Pandya            2
Sandeep Sharma       2
MM Sharma            1
RR Pant              1
SPD Smith            1
S Dhawan             1
KV Sharma            1
MS Dhoni             1
RA Tripathi          1
RG Sharma            1
DA Warner            1
CA Lynn              1
Washington Sundar    1
AT Rayudu            1
HV Patel             1
LH Ferguson          1
GJ Maxwell           1
Yuvraj Singh         1
G Gambhir            1
AR Patel             1
CH Gayle             1
HM Amla              1
KA Pollard           1
MJ McClenaghan       1
SK Raina             1
DR Smith             1
Mohammed Siraj       1
KM Jadhav            1
B Kumar              1
CJ Anderson          1
JJ Bumrah            1
KS Williamson        1
Mohammed Shami       1
KK Nair              1
WP Saha              1
LMP Simmons          1
JC Buttler           1
SS Iyer              1
SV Samson            1
Name: player_of_match, dtype: int64

In [24]:
matches[576:636].player_of_match.value_counts()

V Kohli              5
RG Sharma            4
AB de Villiers       4
DA Warner            3
AD Russell           3
AJ Finch             3
YK Pathan            2
AM Rahane            2
DR Smith             2
B Kumar              2
AB Dinda             2
KH Pandya            2
MP Stoinis           2
CH Morris            2
RV Uthappa           1
MC Henriques         1
A Mishra             1
PA Patel             1
SK Raina             1
AR Patel             1
A Zampa              1
P Kumar              1
Q de Kock            1
CR Brathwaite        1
SA Yadav             1
MS Dhoni             1
HM Amla              1
A Nehra              1
RR Pant              1
Mustafizur Rahman    1
SR Watson            1
BCJ Cutting          1
G Gambhir            1
M Vohra              1
KK Nair              1
SV Samson            1
Name: player_of_match, dtype: int64

In [25]:
mask=matches['city']=='Kolkata'
matches[mask]

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
10,11,2017,Kolkata,2017-04-13,Kings XI Punjab,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,8,SP Narine,Eden Gardens,A Deshmukh,NJ Llong,NaN
13,14,2017,Kolkata,2017-04-15,Kolkata Knight Riders,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Kolkata Knight Riders,17,0,RV Uthappa,Eden Gardens,AY Dandekar,NJ Llong,NaN
22,23,2017,Kolkata,2017-04-21,Kolkata Knight Riders,Gujarat Lions,Gujarat Lions,field,normal,0,Gujarat Lions,0,4,SK Raina,Eden Gardens,CB Gaffaney,Nitin Menon,NaN
26,27,2017,Kolkata,2017-04-23,Kolkata Knight Riders,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Kolkata Knight Riders,82,0,NM Coulter-Nile,Eden Gardens,CB Gaffaney,CK Nandan,NaN
30,31,2017,Kolkata,2017-04-28,Delhi Daredevils,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,7,G Gambhir,Eden Gardens,NJ Llong,S Ravi,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
721,11317,2019,Kolkata,12/04/19,Kolkata Knight Riders,Delhi Capitals,Delhi Capitals,field,normal,0,Delhi Capitals,0,7,S Dhawan,Eden Gardens,Yeshwant Barde,O Nandan,Rod Tucker
724,11320,2019,Kolkata,14/04/19,Kolkata Knight Riders,Chennai Super Kings,Chennai Super Kings,field,normal,0,Chennai Super Kings,0,5,Imran Tahir,Eden Gardens,Rod Tucker,O Nandan,Yeshwant Barde
730,11326,2019,Kolkata,19/04/19,Royal Challengers Bangalore,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Royal Challengers Bangalore,10,0,V Kohli,Eden Gardens,Ian Gould,Nitin Menon,Anil Dandekar
738,11334,2019,Kolkata,25/04/19,Kolkata Knight Riders,Rajasthan Royals,Rajasthan Royals,field,normal,0,Rajasthan Royals,0,3,VR Aaron,Eden Gardens,Ian Gould,Anil Dandekar,Nitin Menon
742,11338,2019,Kolkata,28/04/19,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,normal,0,Kolkata Knight Riders,34,0,AD Russell,Eden Gardens,Ian Gould,Nitin Menon,Anil Dandekar

In [26]:
mask=matches['player_of_match']=='CH Gayle'
matches[mask]

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
19,20,2017,Rajkot,2017-04-18,Royal Challengers Bangalore,Gujarat Lions,Gujarat Lions,field,normal,0,Royal Challengers Bangalore,21,0,CH Gayle,Saurashtra Cricket Association Stadium,S Ravi,VK Sharma,NaN
122,123,2009,Durban,2009-04-21,Kings XI Punjab,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,1,Kolkata Knight Riders,11,0,CH Gayle,Kingsmead,DJ Harper,SD Ranade,NaN
257,258,2011,Kolkata,2011-04-22,Kolkata Knight Riders,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,9,CH Gayle,Eden Gardens,SS Hazare,RB Tiffin,NaN
279,280,2011,Bangalore,2011-05-06,Royal Challengers Bangalore,Kings XI Punjab,Kings XI Punjab,field,normal,0,Royal Challengers Bangalore,85,0,CH Gayle,M Chinnaswamy Stadium,Aleem Dar,RB Tiffin,NaN
282,283,2011,Bangalore,2011-05-08,Kochi Tuskers Kerala,Royal Challengers Bangalore,Kochi Tuskers Kerala,bat,normal,0,Royal Challengers Bangalore,0,9,CH Gayle,M Chinnaswamy Stadium,Aleem Dar,SS Hazare,NaN
290,291,2011,Bangalore,2011-05-14,Kolkata Knight Riders,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,1,Royal Challengers Bangalore,0,4,CH Gayle,M Chinnaswamy Stadium,RE Koertzen,RB Tiffin,NaN
301,302,2011,Bangalore,2011-05-22,Chennai Super Kings,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,8,CH Gayle,M Chinnaswamy Stadium,K Hariharan,RE Koertzen,NaN
305,306,2011,Chennai,2011-05-27,Royal Challengers Bangalore,Mumbai Indians,Mumbai Indians,field,normal,0,Royal Challengers Bangalore,43,0,CH Gayle,"MA Chidambaram Stadium, Chepauk",Asad Rauf,SJA Taufel,NaN
328,329,2012,Bangalore,2012-04-17,Pune Warriors,Royal Challengers Bangalore,Pune Warriors,bat,normal,0,Royal Challengers Bangalore,0,6,CH Gayle,M Chinnaswamy Stadium,S Asnani,S Das,NaN
332,333,2012,Chandigarh,2012-04-20,Kings XI Punjab,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,5,CH Gayle,"Punjab Cricket Association Stadium, Mohali",S Ravi,RJ Tucker,NaN
359,360,2012,Mumbai,2012-05-09,Mumbai Indians,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,9,CH Gayle,Wankhede Stadium,BF Bowden,VA Kulkarni,NaN
361,362,2012,Pune,2012-05-11,Royal Challengers Bangalore,Pune Warriors,Pune Warriors,field,normal,0,Royal Challengers Bangalore,35,0,CH Gayle,Subrata Roy Sahara Stadium,BF Bowden,SK Tarapore,NaN
371,372,2012,Delhi,2012-05-17,Royal Challengers Bangalore,Delhi Daredevils,Delhi Daredevils,field,normal,0,Royal Challengers Bangalore,21,0,CH Gayle,Feroz Shah Kotla,HDPK Dharmasena,C Shamshuddin,NaN
382,383,2013,Bangalore,2013-04-04,Royal Challengers Bangalore,Mumbai Indians,Mumbai Indians,field,normal,0,Royal Challengers Bangalore,2,0,CH Gayle,M Chinnaswamy Stadium,VA Kulkarni,C Shamshuddin,NaN
391,392,2013,Bangalore,2013-04-11,Kolkata Knight Riders,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,8,CH Gayle,M Chinnaswamy Stadium,Asad Rauf,AK Chaudhary,NaN
410,411,2013,Bangalore,2013-04-23,Royal Challengers Bangalore,Pune Warriors,Pune Warriors,field,normal,0,Royal Challengers Bangalore,130,0,CH Gayle,M Chinnaswamy Stadium,Aleem Dar,C Shamshuddin,NaN
521,522,2015,Kolkata,2015-04-11,Kolkata Knight Riders,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,3,CH Gayle,Eden Gardens,S Ravi,C Shamshuddin,NaN
556,557,2015,Bangalore,2015-05-06,Royal Challengers Bangalore,Kings XI Punjab,Kings XI Punjab,field,normal,0,Royal Challengers Bangalore,138,0,CH Gayle,M Chinnaswamy Stadium,RK Illingworth,VA Kulkarni,NaN
647,7905,2018,Mohali,15/04/18,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,field,normal,0,Kings XI Punjab,4,0,CH Gayle,"Punjab Cricket Association IS Bindra Stadium, ...",Vineet Kulkarni,O Nandan,Nigel Llong
651,7909,2018,Mohali,19/04/18,Kings XI Punjab,Sunrisers Hyderabad,Kings XI Punjab,bat,normal,0,Kings XI Punjab,15,0,CH Gayle,"Punjab Cricket Association IS Bindra Stadium, ...",Nigel Llong,Anil Chaudhary,Vineet Kulkarni
699,11140,2019,Jaipur,25/03/19,Kings XI Punjab,Rajasthan Royals,Rajasthan Royals,field,normal,0,Kings XI Punjab,14,0,CH Gayle,Sawai Mansingh Stadium,C Shamshuddin,KN Anantapadmanabhan,Bruce Oxenford

In [27]:
# mask=matches['city']=='Chennai'
# match[mask]
mask=matches['city']=='Chennai'
matches[mask]['player_of_match'].value_counts()

MS Dhoni           5
MEK Hussey         5
SK Raina           4
M Vijay            4
BB McCullum        2
RA Jadeja          2
F du Plessis       2
G Gambhir          2
Harbhajan Singh    2
JA Morkel          2
S Anirudha         1
BW Hilfenhaus      1
J Theron           1
DL Chahar          1
DJ Bravo           1
L Balaji           1
JDP Oram           1
SPD Smith          1
R Ashwin           1
WPUJC Vaas         1
A Nehra            1
CH Gayle           1
MS Bisla           1
RG Sharma          1
ML Hayden          1
A Kumble           1
WP Saha            1
Mandeep Singh      1
HH Pandya          1
AS Yadav           1
RE Levi            1
KMDN Kulasekara    1
SR Watson          1
SW Billings        1
AC Gilchrist       1
KA Pollard         1
V Sehwag           1
Name: player_of_match, dtype: int64

In [28]:
mask = matches['season'] >=2015
mask.value_counts()

False    458
True     298
Name: season, dtype: int64

In [29]:
mask = matches['season'] >=2015
matches[mask]['winner'].value_counts()

Mumbai Indians                 46
Sunrisers Hyderabad            42
Kolkata Knight Riders          39
Royal Challengers Bangalore    31
Chennai Super Kings            31
Kings XI Punjab                26
Delhi Daredevils               23
Rajasthan Royals               19
Gujarat Lions                  13
Rising Pune Supergiant         10
Delhi Capitals                 10
Rising Pune Supergiants         5
Name: winner, dtype: int64

In [31]:
mask1=matches["city"]=="Hyderabad"
mask2=matches["season"]>=2015
matches[mask1 & mask2]["player_of_match"].value_counts()

DA Warner            7
Rashid Khan          4
B Kumar              2
S Dhawan             2
KS Williamson        2
A Joseph             1
Mustafizur Rahman    1
AS Rajpoot           1
JJ Bumrah            1
KH Pandya            1
K Ahmed              1
JD Unadkat           1
J Bairstow           1
Yuvraj Singh         1
CH Morris            1
K Paul               1
AT Rayudu            1
CA Lynn              1
MJ McClenaghan       1
V Kohli              1
AB Dinda             1
G Gambhir            1
Name: player_of_match, dtype: int64